### ISSUE TITLE
MIUI china version not work, 

### ISSUE THREAD

**Issue by Ni1994** [rkhat2/android-rom-repacker#4]
i repack miui rom(cn) by your tools,i got the system.img, then flash it with fastboot mode, The phone is not turned on and is restarted to fastboot mode, so i remove the dm-verify from boot.img by magiskboot and flash boot.img. Now the phone can be turned on, but wifi does not work. Please tell me which step is wrong.sorry for my poor englsh. thanks！

**Comment by rkhat2** [comment]
What steps did you do? Also, I don't have a guide for this tool. You should follow a guide such as [this post](https://forum.xda-developers.com/android/software-hacking/how-to-conver-lollipop-dat-files-to-t2978952) and use my tools when needed. If you get into an issue, post it there.

Unless there is a bug in my tools or need clarification about the functionality of a specific binary, please avoid posting here. Thank you.

**Comment by Ni1994** [comment]
@rkhat2 ok
